# Generated by Django 4.1.4 on 2023-09-09 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_consume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='calorie',
            new_name='calories',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='protien',
            new_name='protein',
        ),
    ]
